name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore Dependencies
        run: |
          dotnet restore EoDData.Net.sln

      - name: Build
        run: |
          dotnet build EoDData.Net.sln --no-restore /WarnAsError --configuration Release

      - name: Test
        env:
          EoDDataUsername: ${{ secrets.EOD_DATA_USERNAME }}
          EoDDataPassword: ${{ secrets.EOD_DATA_PASSWORD }}
          EoDDataBaseUrl: http://ws.eoddata.com/data.asmx/
        run: |
          dotnet test EoDData.Net.Tests/EoDData.Net.Tests.csproj --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:SkipAutoProps=true /p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute\"

      - name: Install SonarQube Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube Scanner
        run: dotnet sonarscanner begin /key:"EoDData.Net" /d:sonar.host.url="${{secrets.SONARQUBE_HOST}}" /d:sonar.login="${{secrets.SONARQUBE_TOKEN}}" /d:sonar.scm.disabled=false /d:sonar.scm.provider=git /d:sonar.links.scm="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" /d:sonar.cs.opencover.reportsPaths='**/coverage.opencover.xml'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release    

      - name: End SonarQube Scanner
        run: dotnet sonarscanner end /d:sonar.login="${{secrets.SONARQUBE_TOKEN}}"
